language: haxe

haxe:
  - 3.4.7
  - development

install:
  - haxelib git hxparse https://github.com/Simn/hxparse --never
  - haxelib git haxeparser https://github.com/Simn/haxeparser --never
  - haxelib git tokentree https://github.com/HaxeCheckstyle/tokentree --never
  - haxelib git hxargs https://github.com/Simn/hxargs --never
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs --never
  - haxelib git mcover https://github.com/massiveinteractive/mcover master src
  - haxelib git munit https://github.com/AlexHaxe/MassiveUnit add_test_filter src
  - haxelib git compiletime https://github.com/andyli/compiletime haxe4 src
  - haxelib git haxe-test-adapter https://github.com/vshaxe/haxe-test-adapter
  - haxelib install json2object
  - haxelib install mlib
  - haxelib install mconsole

script:
  - haxe buildAll.hxml
  - haxe buildTest.hxml -D codecov_json
  - haxe buildSchema.hxml
  - node run.js -s . --check
  - neko run.n -s . --check
  - rm run.js
  - neko run.n -s . --check

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
