language: node_js
node_js:
  - "10"
dist: xenial

env:
  - HAXE_VERSION=haxe347
  - HAXE_VERSION=haxe4
  - HAXE_VERSION=nightly

install:
  - npm install
  - if [[ "$HAXE_VERSION" == "haxe347" ]]; then mv haxe_libraries haxe4_libraries; mv haxe3_libraries haxe_libraries; fi
  - if [[ "$HAXE_VERSION" == "haxe347" ]]; then npx lix download haxe 3.4.7; npx lix use haxe 3.4.7; fi
  - if [[ "$HAXE_VERSION" == "haxe4" ]]; then npx lix download haxe 4.0.3; npx lix use haxe 4.0.3; fi
  - if [[ "$HAXE_VERSION" == "nightly" ]]; then npx lix download haxe nightly; npx lix use haxe nightly; fi
  - npx lix download
  - npx haxe -version
  - npx neko -version
  - npx haxelib list


script:
  - npx haxe buildJsNode.hxml
  - npx haxe buildJsBrowser.hxml
  - npx haxe buildNeko.hxml
  - npx haxe buildJava.hxml
  - npx haxe buildSchema.hxml
  - npx haxe test.hxml -D codecov_json
  - npx haxe testJava.hxml -D codecov_json
  - node run.js -s . --check
  - java -jar out/Cli.jar -s . --check
  - neko run.n -s . --check
  - rm run.js
  - neko run.n -s . --check

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
