name: Haxe-Formatter Linux

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '15 23 * * *'

jobs:
  build:
    strategy:
      matrix:
        haxe-version: ['3.4.7', '4.0.3', 'nightly']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Run npm install
      run: npm ci
    - name: Install Haxe version ${{ matrix.haxe-version }}
      run: |
        npx lix download haxe ${{ matrix.haxe-version }}
        npx lix use haxe ${{ matrix.haxe-version }}
    - name: Prepare Haxe 3 dependencies
      if: matrix.haxe-version == '3.4.7'
      run: |
        mv haxe_libraries haxe4_libraries
        mv haxe3_libraries haxe_libraries
    - name: Run lix download
      run: npx lix download
    - name: Print versions
      run: |
        npx haxe -version
        npx neko -version
        npx haxelib list
    - name: Build NodeJs version
      run: npx haxe buildJsNode.hxml
    - name: Build browser JS version
      run: npx haxe buildJsBrowser.hxml
    - name: Build Neko version
      run: npx haxe buildNeko.hxml
    - name: Build Java version
      run: npx haxe buildJava.hxml
    - name: Build JSON schema
      run: npx haxe buildSchema.hxml
    - name: Run Neko tests
      if: matrix.haxe-version == '3.4.7'
      run: npx haxe -D codecov_json test.hxml
    - name: Run eval tests
      if: matrix.haxe-version != '3.4.7'
      run: npx haxe -D codecov_json test.hxml
    - name: Run Java tests
      run: npx haxe -D codecov_json testJava.hxml
    - name: Run Node version with --check
      run: node run.js -s . --check
    - name: Run Java version with --check
      run: java -jar out/Cli.jar -s . --check
    - name: Run Neko (with node) with --check
      run: |
        npx neko run.n -s . --check
    - name: Run Neko (without node) with --check
      run: |
        rm run.js
        npx neko run.n -s . --check
    - name: Upload results to codecov
      if: success() && matrix.platform == 'ubuntu-latest' && matrix.haxe-version == '4.0.3'
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
